### PR TITLE
Add more room/GC stats on ABCL, CLISP, and ECL.

### PR DESCRIPTION
**Pull request by aartaka**
This adds GC stats on ABCL and CLISP and makes behavior on ECL conditional to Boehm GC. Transplanted from Graven Image.

### CODE REVIEW

**Comment by Shinmera** [comment]
Afaiu ECL without boehm is not supported, so no point in feature-conditioning it.

**Comment by aartaka** [comment]
> Afaiu ECL without boehm is not supported, so no point in feature-conditioning it.

`gc-time` has a Boehm conditional, so I included it for completeness sake.

**Comment by Shinmera** [comment]
Welp, so much for my memory!

**Comment by aartaka** [comment]
No worries and thanks!

**Pull request merged**
